version: '3'
services:
  storage:
    container_name: minio_storage
    image: minio/minio
    restart: always
    command: ["server","/data"]
    ports:
      - "9000:9000"
    volumes:
      - "./data:/data"
    environment:
      MINIO_ACCESS_KEY: MDJ11JSTORAGE
      MINIO_SECRET_KEY: MDJ11JSTORAGESECRET
